version: '3.1'

services:

  db:
    image: mysql
    container_name: fact-core-db
    restart: 'always'
    environment:
      MYSQL_DATABASE: fact-core-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/fact-core
    ports:
      - "8000:8000"
    container_name: fact-core-web
    depends_on:
      - db
